[package]
name = "hir"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lasso = "0.6"
la-arena = "0.2"
smol_str = "0.1"

ast = { path = "../ast" }
syntax = { path = "../syntax" }

[dev-dependencies]
expect-test = "1.4"

parser = { path = "../parser" }
