version: 2
updates:
  - package-ecosystem: cargo
    directory: '/'
    schedule:
      interval: daily
    open-pull-requests-limit: 20
    allow:
      - dependency-type: "all"
    versioning-strategy: auto
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
    open-pull-requests-limit: 20
    allow:
      - dependency-type: "all"
    versioning-strategy: increase
