# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json

language: "ja"

early_access: true

reviews:
  profile: assertive
  request_changes_workflow: true
  high_level_summary: true
  high_level_summary_placeholder: "@coderabbitai summary"
  auto_title_placeholder: "@coderabbitai"
  review_status: true
  commit_status: true
  poem: true
  collapse_walkthrough: true
  sequence_diagrams: true
  changed_files_summary: true
  abort_on_close: true

chat:
  auto_reply: true

enable_free_tier: true

knowledge_base:
  opt_out: false
  learnings:
    scope: local
  issues:
    scope: local
  pull_requests:
    scope: local
