[package]
name = "nail"
version = "0.1.0"
authors = ["ktanaka101 <kentanaka101@gmail.com>"]
edition = "2021"
license = "MIT"

[dependencies]
clap = { workspace = true }
tokio = { workspace = true }

repl = { workspace = true }
lsp = { workspace = true }

[workspace]
members = ["crates/*"]

[workspace.dependencies]
anyhow = "1.0"
clap = { version = "4.1", features = ["derive"] }
drop_bomb = "0.1"
either = "1.8.1"
expect-test = "1.4"
indexmap = "1.9"
inkwell = { git = "https://github.com/TheDan64/inkwell", branch = "master", features = [
  "llvm15-0",
] }
la-arena = "0.2"
lasso = "0.6"
logos = "0.12"
num-derive = "0.3"
num-traits = "0.2"
rowan = "0.15"
smol_str = "0.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
termion = "2.0"
text-size = "1.0"
thiserror = "1.0"
tokio = { version = "1.25", features = ["full"] }
tower-lsp = "0.17"
typed-arena = "2.0"

lexer = { path = "crates/lexer" }
syntax = { path = "crates/syntax" }
parser = { path = "crates/parser" }
ast = { path = "crates/ast" }
hir = { path = "crates/hir" }
hir_ty = { path = "crates/hir_ty" }
mir = { path = "crates/mir" }
codegen_llvm = { path = "crates/codegen_llvm" }
lsp = { path = "crates/lsp" }
repl = { path = "crates/repl" }

[profile.dev]
debug = 0

[profile.dev.package]
logos.opt-level = 3
rowan.opt-level = 3
smol_str.opt-level = 3
text-size.opt-level = 3
