[package]
name = "nail"
version = "0.1.0"
authors = ["ktanaka101 <kentanaka101@gmail.com>"]
edition = "2021"
license = "MIT"

[dependencies]
anyhow = "1.0"
thiserror = "1.0"
inkwell = { git = "https://github.com/TheDan64/inkwell", branch = "master", features = [
  "llvm14-0",
] }
termion = "2.0"
tokio = { version = "1.17.0", features = ["full"] }
typed-arena = "2.0"

lexer = { path = "crates/lexer" }
syntax = { path = "crates/syntax" }
parser = { path = "crates/parser" }
ast = { path = "crates/ast" }
hir = { path = "crates/hir" }
hir_ty = { path = "crates/hir_ty" }
lsp = { path = "crates/lsp" }


[workspace]
members = ["crates/*"]

[profile.dev]
debug = 0

[profile.dev.package]
logos.opt-level = 3
rowan.opt-level = 3
smol_str.opt-level = 3
text-size.opt-level = 3
