[package]
name = "nail"
version = "0.1.0"
authors = ["ktanaka101 <kentanaka101@gmail.com>"]
edition = "2021"
license = "MIT"

[dependencies]
anyhow = "1.0"
thiserror = "1.0"
inkwell = { git = "https://github.com/TheDan64/inkwell", branch = "master", features = [
  "llvm14-0",
] }
termion = "2.0"
typed-arena = "2.0"
rowan = "0.15"
expect-test = "1.4"
drop_bomb = "0.1"

lexer = { path = "crates/lexer" }
syntax = { path = "crates/syntax" }

[workspace]
members = ["crates/*"]
