[package]
name = "nail"
version = "0.1.0"
authors = ["ktanaka101 <kentanaka101@gmail.com>"]
edition = "2018"
license = "MIT"

[dependencies]
anyhow = "1.0"
thiserror = "1.0"
inkwell = { git = "https://github.com/TheDan64/inkwell", branch = "master", features = [
  "llvm11-0",
] }
termion = "1.5"
nom = "7.1"
nom_locate = "4.0"
typed-arena = "2.0"
