# Use cargo-make
# https://github.com/sagiegurari/cargo-make

[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--check"]

[tasks.clippy]
install_crate = "clippy"
command = "cargo"
args = ["clippy", "--", "-D", "warnings"]

[tasks.test]
command = "cargo"
args = ["test"]

[tasks.check]
run_task = { name = ["format", "clippy", "test"], parallel = true }
