[package]
name = "hir_ty"
version = "0.1.0"
edition = "2021"

[dependencies]
la-arena = { workspace = true }

ast = { workspace = true }
hir = { workspace = true }

[dev-dependencies]
expect-test = { workspace = true }

parser = { workspace = true }
