[package]
name = "hir_ty"
version = "0.1.0"
edition = "2021"

[dependencies]
hir = { path = "../hir" }
la-arena = "0.2"

[dev-dependencies]
expect-test = "1.4"

ast = { path = "../ast" }
parser = { path = "../parser" }
