[package]
name = "hir_ty"
version = "0.1.0"
edition = "2021"

[dependencies]
la-arena = { workspace = true }

ast = { path = "../ast" }
hir = { path = "../hir" }

[dev-dependencies]
expect-test = { workspace = true }

parser = { path = "../parser" }
