[package]
name = "ast"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
rowan = { workspace = true }
text-size = { workspace = true }

syntax = { workspace = true }

[dev-dependencies]
parser = { workspace = true }
