[package]
name = "parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
drop_bomb = { workspace = true }
indexmap = { workspace = true }
rowan = { workspace = true }
text-size = { workspace = true }

lexer = { path = "../lexer" }
syntax = { path = "../syntax" }

[dev-dependencies]
expect-test = { workspace = true }
