[package]
name = "lsp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
lsp-types = "0.93"
serde = "1.0"
serde_json = "1.0"
serde_repr = "0.1"
thiserror = "1.0"
