[package]
name = "codegen_llvm"
version = "0.1.0"
edition = "2021"

[dependencies]
inkwell = { git = "https://github.com/TheDan64/inkwell", branch = "master", features = [
  "llvm14-0",
] }

hir = { path = "../hir" }
hir_ty = { path = "../hir_ty" }

[dev-dependencies]
expect-test = "1.4"

ast = { path = "../ast" }
parser = { path = "../parser" }
