[package]
name = "lexer"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }

[lints]
workspace = true

[dependencies]
logos = { workspace = true }
text-size = { workspace = true }
