[package]
name = "base_db"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }

[lints]
workspace = true

[dependencies]
salsa = { workspace = true }

hir = { workspace = true }
hir_ty = { workspace = true }
