[package]
name = "syntax"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }

[lints]
workspace = true

[dependencies]
num-derive = { workspace = true }
num-traits = { workspace = true }
rowan = { workspace = true }

lexer = { workspace = true }
