[package]
name = "syntax"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
num-derive = { workspace = true }
num-traits = { workspace = true }
rowan = { workspace = true }

lexer = { workspace = true }
