name: Nail CI

on:
  pull_request:
    types:
      - opened
      - synchronize
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  RUSTUP_MAX_RETRIES: 10

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ktanaka101/nail/nail-builder:latest

    steps:
      - uses: actions/checkout@v4

      - uses: Swatinem/rust-cache@v2
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: yarn

      # rust tests
      - name: Compile
        run: cargo nextest run --workspace --locked

      - name: Run format
        run: cargo fmt --all -- --check

      - name: Run clippy
        run: cargo clippy --workspace -- -D warnings

      - name: Run nail tests
        run: cargo nextest run --workspace --failure-output immediate-final --no-fail-fast

      # node tests
      - name: Install yarn packages
        run: yarn install --frozen-lockfile

      - name: Run nail language client tests
        run: yarn lsp:test
