name: Nail CI

on:
  pull_request:
    types:
      - opened
      - synchronize
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  RUSTUP_MAX_RETRIES: 10

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ktanaka101/nail/nail-builder:latest

    steps:
      - uses: actions/checkout@v4

      - uses: Swatinem/rust-cache@v2
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: yarn

      # rust tests
      - name: Compile
        run: cargo make nail compile-ci

      - name: Run format
        run: cargo make nail format-ci

      - name: Run clippy
        run: cargo make nail clippy-ci

      - name: Run nail tests
        run: cargo make nail test-ci

      # node tests
      - name: Install yarn packages
        run: cargo make lsp-client install-ci

      - name: Run nail language client tests
        run: cargo make lsp-client test-ci
