name: Nail CI

on:
  pull_request:
    types:
      - opened
      - synchronize
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  RUSTUP_MAX_RETRIES: 10

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker.io/ktanaka101/nail-builder:latest

    steps:
      - uses: actions/checkout@v4

      - uses: Swatinem/rust-cache@v2

      - name: Compile
        run: cargo test --workspace --no-run --locked

      - name: Run format
        run: cargo fmt --all -- --check

      - name: Run clippy
        run: cargo clippy --workspace -- -D warnings

      - name: Run tests
        run: cargo test --workspace -- --nocapture --quiet
